import { db } from './config.js';
import { ref, update } from "https://www.gstatic.com/firebasejs/10.8.1/firebase-database.js";

window.encodeImageFileAsURLNews = async function(element) { let file = element.files[0]; if(!file) return; Swal.showLoading(); try { let url = await window.uploadImageToGitHub(file); document.getElementById('swal-img-b64-news').value = ''; document.getElementById('swal-img-news').value = url; if(document.getElementById('preview-news-img')) document.getElementById('preview-news-img').src = url; } catch(e) { Swal.showValidationMessage(e); } Swal.hideLoading(); };
window.encodeImageFileAsURLNewsAdd = async function(element) { let file = element.files[0]; if(!file) return; Swal.showLoading(); try { let url = await window.uploadImageToGitHub(file); document.getElementById('swal-img-b64-news-add').value = ''; document.getElementById('swal-img-news-add').value = url; if(document.getElementById('preview-news-add-wrapper')) { document.getElementById('preview-news-add-wrapper').classList.remove('d-none'); document.getElementById('preview-news-add-img').src = url; } } catch(e) { Swal.showValidationMessage(e); } Swal.hideLoading(); };
window.encodeImageFileAsURLCNewsAdd = async function(element) { let file = element.files[0]; if(!file) return; Swal.showLoading(); try { let url = await window.uploadImageToGitHub(file); document.getElementById('swal-img-b64-cnews-add').value = ''; document.getElementById('swal-img-cnews-add').value = url; if(document.getElementById('preview-cnews-add-wrapper')) { document.getElementById('preview-cnews-add-wrapper').classList.remove('d-none'); document.getElementById('preview-cnews-add-img').src = url; } } catch(e) { Swal.showValidationMessage(e); } Swal.hideLoading(); };
window.encodeImageFileAsURLCNews = async function(element) { let file = element.files[0]; if(!file) return; Swal.showLoading(); try { let url = await window.uploadImageToGitHub(file); document.getElementById('swal-img-b64-cnews').value = ''; document.getElementById('swal-img-cnews').value = url; if(document.getElementById('preview-cnews-img')) document.getElementById('preview-cnews-img').src = url; } catch(e) { Swal.showValidationMessage(e); } Swal.hideLoading(); };

// MẶC ĐỊNH
window.cmsEditNewsTitle = async () => { const { value: title } = await Swal.fire({ title: 'Sửa Tiêu Đề LLC NEWS', input: 'text', inputValue: window.cmsData.news_data.title, showCancelButton: true }); if(title) { window.cmsData.news_data.title = title; await update(ref(db, 'pageContent/news_data'), window.cmsData.news_data); } };
window.swalDelNewsDirect = async (idx) => { Swal.fire({ title: 'Xóa ảnh này?', icon: 'warning', showCancelButton: true }).then(async (r) => { if(r.isConfirmed) { window.cmsData.news_data.slides.splice(idx, 1); await update(ref(db, 'pageContent/news_data'), window.cmsData.news_data); } }); };
window.swalDelNews = async (idx) => { Swal.fire({ title: 'Xóa ảnh này?', icon: 'warning', showCancelButton: true }).then(async (r) => { if(r.isConfirmed) { window.cmsData.news_data.slides.splice(idx, 1); await update(ref(db, 'pageContent/news_data'), window.cmsData.news_data); let newList = ''; window.cmsData.news_data.slides.forEach((s, i) => { newList += `<tr><td>${i+1}</td><td class="text-start"><img src="${s.img}" style="width:30px; height:30px; object-fit:cover;" class="border rounded"></td><td><button type="button" class="btn btn-sm btn-danger py-0 px-1" onclick="window.swalDelNews(${i})"><i class="bi bi-trash"></i></button></td></tr>`; }); document.getElementById('swal-news-tbody').innerHTML = newList; } }); };
window.cmsAddNewsSlide = async () => {
    let listHTML = ''; if(window.cmsData.news_data.slides) window.cmsData.news_data.slides.forEach((s, i) => { listHTML += `<tr><td>${i+1}</td><td class="text-start"><img src="${s.img}" style="width:30px; height:30px; object-fit:cover;" class="border rounded"></td><td><button type="button" class="btn btn-sm btn-danger py-0 px-1" onclick="window.swalDelNews(${i})"><i class="bi bi-trash"></i></button></td></tr>`; });
    let htmlFull = `<div class="row m-0"><div class="col-md-6 border-end p-0"><div class="text-start pe-2"><div class="text-center mb-2 d-none" id="preview-news-add-wrapper"><img id="preview-news-add-img" src="" style="max-height: 120px; border-radius: 8px; object-fit: contain;"></div><label class="fw-bold mb-1 small">Link Ảnh HOẶC Tải ảnh từ máy:</label><input id="swal-img-news-add" class="form-control form-control-sm mb-2" placeholder="Dán link ảnh..."><input id="swal-img-file-news-add" type="file" class="form-control form-control-sm mb-2" accept="image/*" onchange="encodeImageFileAsURLNewsAdd(this)"><input type="hidden" id="swal-img-b64-news-add" value=""></div></div><div class="col-md-6 p-0"><div class="text-start ps-2" style="max-height: 300px; overflow-y: auto;"><label class="fw-bold mb-2 text-primary small">Dữ liệu hiện tại:</label><table class="table table-sm table-bordered table-hover"><thead class="table-light"><tr><th style="width:40px;">STT</th><th>Ảnh Cover</th><th style="width:40px;">Xóa</th></tr></thead><tbody id="swal-news-tbody">${listHTML}</tbody></table></div></div></div>`;
    const { value: vals } = await Swal.fire({ title: 'Quản Lý Ảnh LLC NEWS', width: '700px', html: htmlFull, showCancelButton: true, confirmButtonText: 'Thêm mới', preConfirm: () => { let b64 = document.getElementById('swal-img-b64-news-add').value; let url = document.getElementById('swal-img-news-add').value; let finalImg = b64 ? b64 : url; if (!finalImg) { Swal.showValidationMessage('Vui lòng chọn ảnh!'); return false; } return { img: finalImg }; } });
    if(vals) { if(!window.cmsData.news_data.slides) window.cmsData.news_data.slides = []; window.cmsData.news_data.slides.push(vals); await update(ref(db, 'pageContent/news_data'), window.cmsData.news_data); Swal.fire({toast:true, position:'top-end', icon:'success', title:'Đã thêm!', showConfirmButton:false, timer:2000}); }
};
window.cmsEditNewsSlide = async (i) => {
    let slide = window.cmsData.news_data.slides[i];
    const { value: vals } = await Swal.fire({ title: 'Sửa Ảnh LLC NEWS', html: `<div class="text-center mb-3"><img id="preview-news-img" src="${slide.img}" style="max-height: 150px; border-radius: 8px; object-fit: contain;"></div><label class="fw-bold d-block text-start small mb-1">Thay thế (Dán Link HOẶC Tải ảnh mới):</label><input id="swal-img-news" class="swal2-input mt-0 mb-2" placeholder="Dán link ảnh..." value="${slide.img || ''}"><input id="swal-img-file-news" type="file" class="form-control w-75 mx-auto mb-3" accept="image/*" onchange="encodeImageFileAsURLNews(this)"><input type="hidden" id="swal-img-b64-news" value="">`, showCancelButton: true, confirmButtonText: 'Lưu thay đổi', preConfirm: () => { let b64 = document.getElementById('swal-img-b64-news').value; let url = document.getElementById('swal-img-news').value; return { img: b64 ? b64 : url }; } });
    if(vals) { window.cmsData.news_data.slides[i] = vals; await update(ref(db, 'pageContent/news_data'), window.cmsData.news_data); Swal.fire({toast:true, position:'top-end', icon:'success', title:'Đã lưu!', showConfirmButton:false, timer:2000}); }
};

// TÙY CHỈNH
window.swalDelCustomNewsDirect = async (idx, bIndex) => { Swal.fire({ title: 'Xóa ảnh này?', icon: 'warning', showCancelButton: true }).then(async (r) => { if(r.isConfirmed) { window.cmsData.custom_blocks[bIndex].slides.splice(idx, 1); await update(ref(db, 'pageContent'), { custom_blocks: window.cmsData.custom_blocks }); } }); };
window.swalDelCustomNews = async (idx, bIndex) => { Swal.fire({ title: 'Xóa ảnh này?', icon: 'warning', showCancelButton: true }).then(async (r) => { if(r.isConfirmed) { window.cmsData.custom_blocks[bIndex].slides.splice(idx, 1); await update(ref(db, 'pageContent'), { custom_blocks: window.cmsData.custom_blocks }); let newList = ''; window.cmsData.custom_blocks[bIndex].slides.forEach((s, i) => { newList += `<tr><td>${i+1}</td><td class="text-start"><img src="${s.img}" style="width:30px; height:30px; object-fit:cover;" class="border rounded"></td><td><button type="button" class="btn btn-sm btn-danger py-0 px-1" onclick="window.swalDelCustomNews(${i}, ${bIndex})"><i class="bi bi-trash"></i></button></td></tr>`; }); document.getElementById('swal-custom-news-tbody').innerHTML = newList; } }); };
window.cmsAddCustomNewsSlide = async (bIndex) => {
    let block = window.cmsData.custom_blocks[bIndex]; if(!block.slides) block.slides = []; let listHTML = ''; block.slides.forEach((s, i) => { listHTML += `<tr><td>${i+1}</td><td class="text-start"><img src="${s.img}" style="width:30px; height:30px; object-fit:cover;" class="border rounded"></td><td><button type="button" class="btn btn-sm btn-danger py-0 px-1" onclick="window.swalDelCustomNews(${i}, ${bIndex})"><i class="bi bi-trash"></i></button></td></tr>`; });
    let htmlFull = `<div class="row m-0"><div class="col-md-6 border-end p-0"><div class="text-start pe-2"><div class="text-center mb-2 d-none" id="preview-cnews-add-wrapper"><img id="preview-cnews-add-img" src="" style="max-height: 120px; border-radius: 8px; object-fit: contain;"></div><label class="fw-bold mb-1 small">Link Ảnh HOẶC Tải ảnh từ máy:</label><input id="swal-img-cnews-add" class="form-control form-control-sm mb-2" placeholder="Dán link ảnh..."><input id="swal-img-file-cnews-add" type="file" class="form-control form-control-sm mb-2" accept="image/*" onchange="encodeImageFileAsURLCNewsAdd(this)"><input type="hidden" id="swal-img-b64-cnews-add" value=""></div></div><div class="col-md-6 p-0"><div class="text-start ps-2" style="max-height: 300px; overflow-y: auto;"><label class="fw-bold mb-2 text-primary small">Dữ liệu hiện tại:</label><table class="table table-sm table-bordered table-hover"><thead class="table-light"><tr><th style="width:40px;">STT</th><th>Ảnh Cover</th><th style="width:40px;">Xóa</th></tr></thead><tbody id="swal-custom-news-tbody">${listHTML}</tbody></table></div></div></div>`;
    const { value: vals } = await Swal.fire({ title: 'Quản Lý Ảnh NEWS Mới', width: '700px', html: htmlFull, showCancelButton: true, confirmButtonText: 'Thêm mới', preConfirm: () => { let b64 = document.getElementById('swal-img-b64-cnews-add').value; let url = document.getElementById('swal-img-cnews-add').value; let finalImg = b64 ? b64 : url; if (!finalImg) { Swal.showValidationMessage('Vui lòng chọn ảnh!'); return false; } return { img: finalImg }; } });
    if(vals) { window.cmsData.custom_blocks[bIndex].slides.push(vals); await update(ref(db, 'pageContent'), { custom_blocks: window.cmsData.custom_blocks }); Swal.fire({toast:true, position:'top-end', icon:'success', title:'Đã thêm!', showConfirmButton:false, timer:2000}); }
};
window.cmsEditCustomNewsSlide = async (idx, bIndex) => {
    let slide = window.cmsData.custom_blocks[bIndex].slides[idx];
    const { value: vals } = await Swal.fire({ title: 'Sửa Ảnh NEWS', html: `<div class="text-center mb-3"><img id="preview-cnews-img" src="${slide.img}" style="max-height: 150px; border-radius: 8px; object-fit: contain;"></div><label class="fw-bold d-block text-start small mb-1">Thay thế (Link HOẶC Tải ảnh):</label><input id="swal-img-cnews" class="swal2-input mt-0 mb-2" value="${slide.img || ''}"><input id="swal-img-file-cnews" type="file" class="form-control w-75 mx-auto mb-3" accept="image/*" onchange="encodeImageFileAsURLCNews(this)"><input type="hidden" id="swal-img-b64-cnews" value="">`, showCancelButton: true, confirmButtonText: 'Lưu thay đổi', preConfirm: () => { let b64 = document.getElementById('swal-img-b64-cnews').value; let url = document.getElementById('swal-img-cnews').value; return { img: b64 ? b64 : url }; } });
    if(vals) { window.cmsData.custom_blocks[bIndex].slides[idx] = vals; await update(ref(db, 'pageContent'), { custom_blocks: window.cmsData.custom_blocks }); }
};