import { db } from './config.js';
import { ref, update } from "https://www.gstatic.com/firebasejs/10.8.1/firebase-database.js";

window.encodeImageFileAsURLTeacher = async function(element) { let file = element.files[0]; if(!file) return; Swal.showLoading(); try { let url = await window.uploadImageToGitHub(file); document.getElementById('swal-img-b64-teacher').value = ''; document.getElementById('swal-img-teacher').value = url; if(document.getElementById('preview-teacher-img')) document.getElementById('preview-teacher-img').src = url; } catch(e) { Swal.showValidationMessage(e); } Swal.hideLoading(); };
window.encodeImageFileAsURLTeacherAdd = async function(element) { let file = element.files[0]; if(!file) return; Swal.showLoading(); try { let url = await window.uploadImageToGitHub(file); document.getElementById('swal-img-b64-teacher-add').value = ''; document.getElementById('swal-img-teacher-add').value = url; if(document.getElementById('preview-teacher-add-wrapper')) { document.getElementById('preview-teacher-add-wrapper').classList.remove('d-none'); document.getElementById('preview-teacher-add-img').src = url; } } catch(e) { Swal.showValidationMessage(e); } Swal.hideLoading(); };

window.cmsDeleteGlobalTeacher = async () => { Swal.fire({title:'Xóa vĩnh viễn khối này?', icon:'warning', showCancelButton:true}).then(async (r)=>{ if(r.isConfirmed) { window.cmsData.teacher_data.isDeleted = true; await update(ref(db, 'pageContent/teacher_data'), window.cmsData.teacher_data); Swal.fire('Đã xóa', '', 'success'); } }); };

window.cmsEditTeacherTitle = async (bIndex = null) => {
    let tConf = bIndex !== null ? window.cmsData.custom_blocks[bIndex] : (window.cmsData.teacher_data || { title: "Đội Ngũ Giảng Viên", icon: "bi-person-video3", color: "#00d5ff" });
    let iconsArr = ['bi-person-video3', 'bi-people-fill', 'bi-mortarboard-fill', 'bi-award-fill', 'bi-star-fill', 'bi-gem', 'bi-heart-fill', 'bi-lightning-charge-fill'];
    let iconGrid = `<div id="icon-picker" class="d-flex flex-wrap gap-2 mb-3 justify-content-center p-2 rounded bg-light border">` + iconsArr.map(i => `<i class="bi ${i} fs-3 p-2 border rounded bg-white icon-option ${tConf.icon === i ? 'border-primary border-3' : ''}" style="cursor:pointer;" onclick="selectIcon('${i}', event)"></i>`).join('') + `</div><input type="hidden" id="swal-icon" value="${tConf.icon}">`;
    const { value: vals } = await Swal.fire({ title: 'Tùy chỉnh Khối Giảng Viên', html: `<div class="text-start fw-bold mb-2">Tiêu đề khối:</div><input id="swal-t-title-main" class="swal2-input mt-0 mb-3" placeholder="Nhập tiêu đề..." value="${tConf.title || ''}"><div class="text-start fw-bold mb-2">Chọn Icon:</div>${iconGrid}<div class="text-start fw-bold mb-2">Màu sắc chủ đạo:</div><input type="color" id="swal-t-colormain" value="${tConf.color || '#00d5ff'}" class="form-control form-control-color w-100">`, showCancelButton: true, preConfirm: () => { return { title: document.getElementById('swal-t-title-main').value, icon: document.getElementById('swal-icon').value, color: document.getElementById('swal-t-colormain').value } } });
    if (vals) { if (bIndex !== null) { window.cmsData.custom_blocks[bIndex].title = vals.title; window.cmsData.custom_blocks[bIndex].icon = vals.icon; window.cmsData.custom_blocks[bIndex].color = vals.color; await update(ref(db, 'pageContent'), { custom_blocks: window.cmsData.custom_blocks }); } else { window.cmsData.teacher_data.title = vals.title; window.cmsData.teacher_data.icon = vals.icon; window.cmsData.teacher_data.color = vals.color; await update(ref(db, 'pageContent/teacher_data'), window.cmsData.teacher_data); } Swal.fire({toast:true, position:'top-end', icon:'success', title:'Đã lưu!', showConfirmButton:false, timer:2000}); }
};

window.cmsDeleteTeacherCard = async (index, bIndex = null) => {
    Swal.fire({title: 'Xóa giáo viên này?', icon: 'warning', showCancelButton: true}).then(async (r) => { if (r.isConfirmed) { if (bIndex !== null) { window.cmsData.custom_blocks[bIndex].cards.splice(index, 1); await update(ref(db, 'pageContent'), { custom_blocks: window.cmsData.custom_blocks }); } else { window.cmsData.teacher_data.cards.splice(index, 1); await update(ref(db, 'pageContent/teacher_data'), window.cmsData.teacher_data); } Swal.fire('Đã xóa', '', 'success'); } });
};

window.swalDelTeacher = async (idx, bIdx) => {
    if(confirm('Bạn có chắc chắn xóa giáo viên này?')) {
        let cards = []; if (bIdx !== null) { window.cmsData.custom_blocks[bIdx].cards.splice(idx, 1); await update(ref(db, 'pageContent'), { custom_blocks: window.cmsData.custom_blocks }); cards = window.cmsData.custom_blocks[bIdx].cards; } else { window.cmsData.teacher_data.cards.splice(idx, 1); await update(ref(db, 'pageContent/teacher_data'), window.cmsData.teacher_data); cards = window.cmsData.teacher_data.cards; }
        let newList = ''; cards.forEach((c, i) => { newList += `<tr><td>${i+1}</td><td class="text-start"><img src="${c.img || 'https://via.placeholder.com/150'}" style="width:30px; height:30px; object-fit:cover; background:#f4f4f4;" class="me-1 border rounded"><span class="small">${c.name || 'Tên giáo viên'}</span></td><td><button type="button" class="btn btn-sm btn-danger py-0 px-1" onclick="window.swalDelTeacher(${i}, ${bIdx})"><i class="bi bi-trash"></i></button></td></tr>`; }); document.getElementById('swal-teacher-tbody').innerHTML = newList;
    }
};

window.cmsAddTeacherCard = async (bIndex = null) => {
    let cards = bIndex !== null ? (window.cmsData.custom_blocks[bIndex].cards || []) : (window.cmsData.teacher_data && window.cmsData.teacher_data.cards ? window.cmsData.teacher_data.cards : []);
    let listHTML = ''; cards.forEach((c, i) => { listHTML += `<tr><td>${i+1}</td><td class="text-start"><img src="${c.img || 'https://via.placeholder.com/150'}" style="width:30px; height:30px; object-fit:cover; background:#f4f4f4;" class="me-1 border rounded"><span class="small">${c.name || 'Tên giáo viên'}</span></td><td><button type="button" class="btn btn-sm btn-danger py-0 px-1" onclick="window.swalDelTeacher(${i}, ${bIndex})"><i class="bi bi-trash"></i></button></td></tr>`; });
    let leftCol = `<div class="text-start pe-2"><div class="text-center mb-2 d-none" id="preview-teacher-add-wrapper"><img id="preview-teacher-add-img" src="" style="max-height: 120px; border-radius: 8px; object-fit: contain; background: #f4f4f4;"></div><label class="fw-bold mb-1 small text-danger"><i class="bi bi-info-circle"></i> Tải ảnh hoặc Dán link (Chuẩn: 298x500):</label><input id="swal-img-teacher-add" class="form-control form-control-sm mb-1" placeholder="Dán link ảnh..."><input id="swal-img-file-teacher-add" type="file" class="form-control form-control-sm mb-2" accept="image/*" onchange="encodeImageFileAsURLTeacherAdd(this)"><input type="hidden" id="swal-img-b64-teacher-add" value=""><input id="swal-t-name-add" class="form-control form-control-sm mb-2 mt-3" placeholder="Tên Giáo Viên (vd: NGUYỄN VĂN A)"><div class="row g-1 mb-2 text-start"><div class="col-4"><label class="fw-bold small" style="font-size:11px;">Màu tên:</label><input type="color" id="swal-t-namecol-add" value="#112255" class="form-control form-control-color form-control-sm w-100 p-0"></div><div class="col-4"><label class="fw-bold small" style="font-size:11px;">Màu chức vụ:</label><input type="color" id="swal-t-rolecol-add" value="#112255" class="form-control form-control-color form-control-sm w-100 p-0"></div><div class="col-4"><label class="fw-bold small" style="font-size:11px;">Nền dưới:</label><input type="color" id="swal-t-bgcol-add" value="#1d73dd" class="form-control form-control-color form-control-sm w-100 p-0"></div></div><input id="swal-t-role-add" class="form-control form-control-sm mb-2" placeholder="Chức vụ (vd: Giáo viên)"><input id="swal-t-exp-add" class="form-control form-control-sm mb-2" placeholder="Số năm kinh nghiệm (vd: 8)"><div class="form-check form-switch text-start"><input class="form-check-input" type="checkbox" id="swal-t-hideexp-add"><label class="form-check-label fw-bold small text-danger" for="swal-t-hideexp-add">Ẩn khung đỏ Kinh nghiệm</label></div></div>`;
    let rightCol = `<div class="text-start ps-2" style="max-height: 400px; overflow-y: auto;"><label class="fw-bold mb-2 text-primary small">Dữ liệu hiện tại:</label><table class="table table-sm table-bordered table-hover"><thead class="table-light"><tr><th style="width:40px;">STT</th><th>Giáo viên</th><th style="width:40px;">Xóa</th></tr></thead><tbody id="swal-teacher-tbody">${listHTML}</tbody></table></div>`;
    const { value: vals } = await Swal.fire({ title: 'Quản Lý Giáo Viên', width: '900px', html: `<div class="row m-0"><div class="col-md-6 border-end p-0">${leftCol}</div><div class="col-md-6 p-0">${rightCol}</div></div>`, showCancelButton: true, confirmButtonText: 'Thêm mới', preConfirm: () => { let b64 = document.getElementById('swal-img-b64-teacher-add').value; let url = document.getElementById('swal-img-teacher-add').value; let finalImg = b64 ? b64 : (url ? url : ""); let inputName = document.getElementById('swal-t-name-add').value; if(!inputName && !finalImg) { Swal.showValidationMessage('Vui lòng nhập Tên hoặc chọn ảnh!'); return false; } return { name: inputName || '', role: document.getElementById('swal-t-role-add').value || '', experience: document.getElementById('swal-t-exp-add').value || '', img: finalImg, hideExperience: document.getElementById('swal-t-hideexp-add').checked, nameColor: document.getElementById('swal-t-namecol-add').value, roleColor: document.getElementById('swal-t-rolecol-add').value, bgColor: document.getElementById('swal-t-bgcol-add').value }; } });
    if(vals) { if (bIndex !== null) { if (!window.cmsData.custom_blocks[bIndex].cards) window.cmsData.custom_blocks[bIndex].cards = []; window.cmsData.custom_blocks[bIndex].cards.push(vals); await update(ref(db, 'pageContent'), { custom_blocks: window.cmsData.custom_blocks }); } else { if (!window.cmsData.teacher_data) window.cmsData.teacher_data = { cards: [] }; if (!window.cmsData.teacher_data.cards) window.cmsData.teacher_data.cards = []; window.cmsData.teacher_data.cards.push(vals); await update(ref(db, 'pageContent/teacher_data'), window.cmsData.teacher_data); } Swal.fire({toast:true, position:'top-end', icon:'success', title:'Đã thêm!', showConfirmButton:false, timer:2000}); }
};

window.cmsEditTeacherCard = async (index, bIndex = null) => {
    let card = bIndex !== null ? window.cmsData.custom_blocks[bIndex].cards[index] : (window.cmsData.teacher_data.cards[index] || {});
    let imgInputHtml = `<div class="text-center mb-3 mt-3"><label class="fw-bold d-block mb-2 text-primary">Ảnh hiện tại:</label><img id="preview-teacher-img" src="${card.img || 'https://via.placeholder.com/298x500'}" style="max-height: 120px; border-radius: 8px; object-fit: contain; background: #f4f4f4;"></div><div class="mb-2 text-start mt-3"><label class="fw-bold fs-6 text-danger"><i class="bi bi-info-circle"></i> Tải ảnh hoặc Dán link (Chuẩn: 298x500):</label></div><input id="swal-img-teacher" class="swal2-input mt-0 mb-2" placeholder="Dán link ảnh..." value="${card.img || ''}"><input id="swal-img-file-teacher" type="file" class="form-control w-75 mx-auto mb-3" accept="image/*" onchange="encodeImageFileAsURLTeacher(this)"><input type="hidden" id="swal-img-b64-teacher" value="">`;
    let htmlForm = `<input id="swal-t-name" class="swal2-input mt-0" placeholder="Tên Giáo Viên (Vd: NGUYỄN VĂN A)" value="${card.name || ''}"><div class="row px-4 mt-2 mb-2 text-start"><div class="col-6"><label class="fw-bold fs-6">Màu tên:</label><input type="color" id="swal-t-namecol" value="${card.nameColor || '#112255'}" class="form-control form-control-color w-100"></div><div class="col-6"><label class="fw-bold fs-6">Màu chức vụ:</label><input type="color" id="swal-t-rolecol" value="${card.roleColor || '#112255'}" class="form-control form-control-color w-100"></div><div class="col-12 mt-2"><label class="fw-bold fs-6">Màu nền khung dưới:</label><input type="color" id="swal-t-bgcol" value="${card.bgColor || '#1d73dd'}" class="form-control form-control-color w-100"></div></div><input id="swal-t-role" class="swal2-input" placeholder="Chức vụ (vd: Giáo viên)" value="${card.role || ''}"><input id="swal-t-exp" class="swal2-input" placeholder="Số năm kinh nghiệm (vd: 8)" value="${card.experience || ''}"><div class="form-check form-switch text-start px-4 mt-2 mb-2"><input class="form-check-input" type="checkbox" id="swal-t-hideexp" ${card.hideExperience ? 'checked' : ''} style="margin-left: -2em;"><label class="form-check-label fw-bold ms-2 text-danger" for="swal-t-hideexp">Ẩn khung đỏ Kinh nghiệm</label></div>${imgInputHtml}`;
    const { value: vals } = await Swal.fire({ title: 'Sửa Giáo Viên', html: htmlForm, focusConfirm: false, showCancelButton: true, confirmButtonText: 'Lưu thay đổi', preConfirm: () => { let b64 = document.getElementById('swal-img-b64-teacher').value; let url = document.getElementById('swal-img-teacher').value; return { name: document.getElementById('swal-t-name').value, role: document.getElementById('swal-t-role').value, experience: document.getElementById('swal-t-exp').value, img: b64 ? b64 : url, hideExperience: document.getElementById('swal-t-hideexp').checked, nameColor: document.getElementById('swal-t-namecol').value, roleColor: document.getElementById('swal-t-rolecol').value, bgColor: document.getElementById('swal-t-bgcol').value }; } });
    if (vals) { if (bIndex !== null) { window.cmsData.custom_blocks[bIndex].cards[index] = vals; await update(ref(db, 'pageContent'), { custom_blocks: window.cmsData.custom_blocks }); } else { window.cmsData.teacher_data.cards[index] = vals; await update(ref(db, 'pageContent/teacher_data'), window.cmsData.teacher_data); } Swal.fire({toast:true, position:'top-end', icon:'success', title:'Đã lưu!', showConfirmButton:false, timer:2000}); }
};